apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - command:
    - redis-server
    - /redis-master/redis.conf
    env:
    - name: MASTER
      value: 'true'
    image: redis:5.0.4
    name: redis
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: '0.1'
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
  - configMap: null
    emptyDir: {}
    name: data
  - configMap:
      items:
      - key: redis-config
        path: redis.conf
      name: example-redis-config
    emptyDir: null
    name: config
